/**
 * One-Key Report helpers — turn the reviewed aerial photos into deliverables:
 * a CSV/printable image list, an aerial-photo-interpretation report, and a
 * two-photo change description. Pure data/formatting (no DOM side effects
 * beyond the download/print helpers at the bottom).
 */

const YEAR_RE = /(?:^|[^\d])(19\d\d|20\d\d)(?:[^\d]|$)/;

/** Best-effort flight year for a photo (index meta first, then filename). */
export function photoYear(a) {
  if (a?.meta?.year) return Number(a.meta.year);
  const m = String(a?.filename ?? '').match(YEAR_RE);
  return m ? Number(m[1]) : null;
}

/** Rows for the image-list table: [{ id, scale, flyingHt, year }]. */
export function imageListRows(aerials) {
  return aerials.map((a) => ({
    id: a.photono || a.filename,
    scale: a.meta?.scale ? `1:${a.meta.scale}` : '—',
    flyingHt: a.meta?.flyingHt != null ? `${a.meta.flyingHt} ft` : '—',
    year: photoYear(a) ?? '—',
  }));
}

/** Escape a value for CSV (quote when it contains a comma/quote/newline). */
function csvCell(v) {
  const s = String(v ?? '');
  return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
}

/** CSV text for the image list (Image ID, Scale, Flight Height, Year). */
export function imageListCsv(aerials) {
  const header = ['Image No. / ID', 'Scale', 'Flight Height', 'Year'];
  const lines = [header.join(',')];
  for (const r of imageListRows(aerials)) {
    lines.push([r.id, r.scale, r.flyingHt, r.year].map(csvCell).join(','));
  }
  return lines.join('\r\n');
}

/**
 * Aerial-photo-interpretation report as HTML. `opts`:
 *   { title, location, area (EPSG:2326 extent), photosByYear: Map<year, [a]>,
 *     preparedBy }
 * Structured like a standard SMO interpretation report — the caller supplies
 * observations per year (free text), everything else is filled from metadata.
 */
export function buildReportHtml({ title, location, area, groups, preparedBy, observations }) {
  const today = new Date().toISOString().slice(0, 10);
  const areaLine = area
    ? `HK1980 Grid extent: [${area.map((v) => v.toFixed(0)).join(', ')}] (E,N metres)`
    : 'Whole uploaded set';
  const yearBlocks = groups
    .map(({ year, photos }) => {
      const rows = photos
        .map(
          (a) =>
            `<tr><td>${a.photono || a.filename}</td>` +
            `<td>${a.meta?.scale ? '1:' + a.meta.scale : '—'}</td>` +
            `<td>${a.meta?.flyingHt != null ? a.meta.flyingHt + ' ft' : '—'}</td></tr>`
        )
        .join('');
      const note = (observations && observations[year]) || '';
      return `
        <section class="year">
          <h3>${year}</h3>
          <table>
            <thead><tr><th>Photo No.</th><th>Scale</th><th>Flying height</th></tr></thead>
            <tbody>${rows}</tbody>
          </table>
          <p class="obs"><b>Observations:</b> ${note ? escapeHtml(note) : '<i>(add site observations)</i>'}</p>
        </section>`;
    })
    .join('');

  return `<!doctype html><html><head><meta charset="utf-8"><title>${escapeHtml(
    title
  )}</title><style>
    body{font-family:Georgia,serif;color:#111;max-width:800px;margin:24px auto;padding:0 16px;line-height:1.5}
    h1{font-size:20px;border-bottom:2px solid #333;padding-bottom:6px}
    h3{font-size:15px;margin:18px 0 6px;color:#1e3a5f}
    table{border-collapse:collapse;width:100%;font-size:13px;margin:6px 0}
    th,td{border:1px solid #999;padding:4px 8px;text-align:left}
    th{background:#eef}
    .meta{font-size:12px;color:#444}
    .obs{font-size:13px}
    footer{margin-top:24px;font-size:11px;color:#666;border-top:1px solid #ccc;padding-top:8px}
  </style></head><body>
    <h1>${escapeHtml(title)}</h1>
    <p class="meta">
      Location: ${escapeHtml(location || '—')}<br>
      ${areaLine}<br>
      Years covered: ${groups.map((g) => g.year).join(', ') || '—'}<br>
      Prepared by: ${escapeHtml(preparedBy || '—')} · Date: ${today}
    </p>
    ${yearBlocks}
    <footer>
      Aerial photographs © Survey &amp; Mapping Office, Lands Department, HKSAR.
      Footprints &amp; metadata from HKMS 2.0. Generated by the HKMS Aerial Photo
      Georeferencer.
    </footer>
  </body></html>`;
}

/** Computed facts for a two-photo change description (the rest is user text). */
export function changeFacts(a, b) {
  const ya = photoYear(a);
  const yb = photoYear(b);
  const overlap = a.extent && b.extent ? extentOverlapRatio(a.extent, b.extent) : null;
  return {
    a: { id: a.photono || a.filename, year: ya, scale: a.meta?.scale },
    b: { id: b.photono || b.filename, year: yb, scale: b.meta?.scale },
    yearGap: ya != null && yb != null ? Math.abs(yb - ya) : null,
    sameArea: overlap != null ? overlap > 0.6 : null,
    overlapPct: overlap != null ? Math.round(overlap * 100) : null,
  };
}

function extentOverlapRatio(e1, e2) {
  const ix = Math.max(0, Math.min(e1[2], e2[2]) - Math.max(e1[0], e2[0]));
  const iy = Math.max(0, Math.min(e1[3], e2[3]) - Math.max(e1[1], e2[1]));
  const inter = ix * iy;
  const a1 = (e1[2] - e1[0]) * (e1[3] - e1[1]);
  const a2 = (e2[2] - e2[0]) * (e2[3] - e2[1]);
  const uni = a1 + a2 - inter;
  return uni > 0 ? inter / uni : 0;
}

function escapeHtml(s) {
  return String(s ?? '').replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]));
}

/* --------------------------- browser side-effects -------------------------- */

/** Trigger a text-file download. */
export function downloadText(filename, text, mime = 'text/plain') {
  const blob = new Blob([text], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

/** Open an HTML report in a new tab for printing / saving as PDF. */
export function openHtmlReport(html) {
  const w = window.open('', '_blank');
  if (!w) return false;
  w.document.write(html);
  w.document.close();
  return true;
}
